import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/modules/core/providers/SessionProvider";
import {ThemeProvider} from "@/modules/core/providers/ThemeProvider";
import Header from "@/modules/core/components/Header/Header";
import Footer from "@/modules/core/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html
        lang="en"
        suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AuthProvider>
          <ThemeProvider
              attribute={"class"}
              defaultTheme={"system"}
              enableSystem={true}
              disableTransitionOnChange={true}
          >
              <Header/>
              <main className="">
                {children}
              </main>
              <Footer/>

          </ThemeProvider>
      </AuthProvider>
      </body>
    </html>
  );
}
